name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    - 'hiep-build'
    tags:
    - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    secrets: inherit
    with:
      go-version: '1.23'
      go-lint-version: 'v1.60.2'
      run-unit-tests: true
      run-integration-tests: false
      run-lint: true

  docker_testnet_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.12.0
    secrets: inherit
    permissions:
      # required for all workflows
      security-events: write
      # required to fetch internal or private CodeQL packs
      packages: read
    with:
      publish: true
      dockerfile: ./contrib/images/babylond/Dockerfile
      repoName: babylond
      imageTag: v1.0.0-rc.6-hot-fix-testnet
      buildArgs: |
        BABYLON_BUILD_OPTIONS=testnet
      docker_scan: true
